version: '3.7'
 
services:
    backend:
        build:
            context: ./backend
        networks:
            - my-network
        ports:
            - "8088:8080"
        depends_on:
            - database
        container_name : backend-container
 
    database:
        build:
            context: ./database
        networks:
            - my-network
        volumes:
            - my-volume:/var/lib/postgresql/data
        container_name : database-container
 
    httpd:
        build:
            context: ./frontend
        ports:
            - "80:80"
        networks:
            - my-network
        depends_on:
            - backend
        container_name : frontend-container

    front:
        build:
            context: ./devops-front-main
        ports:
            - "8080:80"
        networks:
            - my-network
        depends_on:
            - httpd
        container_name : devops-front-container
 
networks:
    my-network:

volumes:
    my-volume: