name: CI devops 2024

on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0
      - name: Set up JDK 17
        #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test with Maven
        run: mvn clean verify -f "./backend/pom.xml"

  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    needs: test-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: "./backend"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-compose-backend:latest

      - name: Build and push database image
        uses: docker/build-push-action@v2
        with:
          context: "./database"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-compose-database:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: "./frontend"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-compose-frontend:latest


