name: CI devops 2024

on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0
      - name: Set up JDK 22
        #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build and test with Maven
        run: mvn clean verify -f "C:\Users\assel\Documents\EPF-MDE-DevOps-ASSELE-Maria\Docker-compose\backend\pom.xml"
